<Project>
  <PropertyGroup>
    <TargetFrameworks>net11.0-android</TargetFrameworks>
    <TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);net11.0-ios;net11.0-maccatalyst</TargetFrameworks>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net11.0-windows10.0.19041.0</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ContinuousIntegrationBuild)' == 'true' and '$(TargetFramework)' == 'net11.0-ios' and $([MSBuild]::IsOSPlatform('osx'))">
    <RuntimeIdentifier>iossimulator-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="'$([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture)' == 'Arm64'">iossimulator-arm64</RuntimeIdentifier>
  </PropertyGroup>
</Project>
