#!/usr/bin/env swift

import AppKit
import Foundation
import Vision

struct SlideText {
    let number: Int
    let lines: [String]
}

func usage() -> Never {
    FileHandle.standardError.write(
        Data("Usage: extract_rendered_slide_text.swift <image-directory> <output.md>\n".utf8)
    )
    exit(2)
}

guard CommandLine.arguments.count == 3 else {
    usage()
}

let inputDirectory = URL(fileURLWithPath: CommandLine.arguments[1], isDirectory: true)
let outputFile = URL(fileURLWithPath: CommandLine.arguments[2])
let fileManager = FileManager.default

guard let files = try? fileManager.contentsOfDirectory(
    at: inputDirectory,
    includingPropertiesForKeys: nil,
    options: [.skipsHiddenFiles]
) else {
    FileHandle.standardError.write(
        Data("Unable to read image directory: \(inputDirectory.path)\n".utf8)
    )
    exit(1)
}

let slideImages = files
    .filter { ["png", "jpg", "jpeg"].contains($0.pathExtension.lowercased()) }
    .sorted { $0.lastPathComponent.localizedStandardCompare($1.lastPathComponent) == .orderedAscending }

guard !slideImages.isEmpty else {
    FileHandle.standardError.write(
        Data("No slide images found in: \(inputDirectory.path)\n".utf8)
    )
    exit(1)
}

func recognizeText(in imageURL: URL) throws -> [String] {
    guard
        let image = NSImage(contentsOf: imageURL),
        let imageData = image.tiffRepresentation,
        let bitmap = NSBitmapImageRep(data: imageData),
        let cgImage = bitmap.cgImage
    else {
        throw NSError(
            domain: "SlideOCR",
            code: 1,
            userInfo: [NSLocalizedDescriptionKey: "Unable to decode \(imageURL.path)"]
        )
    }

    let request = VNRecognizeTextRequest()
    request.recognitionLevel = .accurate
    request.recognitionLanguages = ["en-US"]
    request.usesLanguageCorrection = true

    let handler = VNImageRequestHandler(cgImage: cgImage, options: [:])
    try handler.perform([request])

    return (request.results ?? [])
        .compactMap { $0.topCandidates(1).first?.string }
        .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
        .filter { !$0.isEmpty }
}

var slides: [SlideText] = []

for (index, imageURL) in slideImages.enumerated() {
    do {
        slides.append(SlideText(number: index + 1, lines: try recognizeText(in: imageURL)))
    } catch {
        FileHandle.standardError.write(
            Data("OCR failed for \(imageURL.lastPathComponent): \(error.localizedDescription)\n".utf8)
        )
        exit(1)
    }
}

var markdown = """
# Visual text from rendered source slides

Generated by rendering every slide from `copilot-app-english.pptx` and running
macOS Vision text recognition over the complete slide image. This captures text
inside screenshots, diagrams, and flattened artwork that the PPTX XML extractor
cannot see.

OCR is supporting evidence, not authoritative transcription. Verify wording
against the rendered slide before quoting it verbatim.

"""

for slide in slides {
    markdown += "\n## Slide \(slide.number)\n\n"
    if slide.lines.isEmpty {
        markdown += "_No visual text recognized._\n"
    } else {
        markdown += slide.lines.map { "- \($0)" }.joined(separator: "\n")
        markdown += "\n"
    }
}

do {
    try markdown.write(to: outputFile, atomically: true, encoding: .utf8)
} catch {
    FileHandle.standardError.write(
        Data("Unable to write \(outputFile.path): \(error.localizedDescription)\n".utf8)
    )
    exit(1)
}

